# Primary backend configurations for LLM API endpoints
primary_backends:
  # First backend configuration
  - name: LLM1  # Identifier for the first backend
    url: http://localhost:11434/v1  # API endpoint URL
    model: "deepseek-r1:1.5b"  # Model to use
  
  # Second backend configuration
  - name: LLM2  # Identifier for the second backend
    url: http://localhost:11434/v1  # API endpoint URL
    model: "deepseek-r1:1.5b"  # Model to use

  # Third backend configuration
  - name: LLM3  # Identifier for the second backend
    url: http://localhost:11434/v1  # API endpoint URL
    model: "deepseek-r1:1.5b"  # Model to use

iterations:
    aggregation:
      strategy: concatenate
      separator: "-------------"


# Global settings
settings:
  timeout: 30  # Request timeout in seconds 